name: pipeline

on:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1

      - run: flutter upgrade
      - run: flutter pub get
      - run: flutter test
      - run: flutter build web
    
      - uses: codecov/codecov-action@v1
        with: 
          token: ${{secrets.CODECOV}}
          file: ./coverage/lcov.info



